# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "JOSSOAgentForROR"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ben Walding"]
  s.date = "2012-06-08"
  s.description = "Ruby JoSSO driver"
  s.email = "ben@walding.com"
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "MIT-LICENSE",
    "README",
    "Rakefile",
    "VERSION",
    "config/josso_config.yml",
    "init.rb",
    "install.rb",
    "lib/SSOIdentityManagerWSClient.rb",
    "lib/SSOIdentityProviderWSClient.rb",
    "lib/josso_agent.rb",
    "lib/josso_classes.rb",
    "lib/main.rb",
    "lib/sso_identity_manager.rb",
    "lib/sso_identity_manager_classes.rb",
    "lib/sso_identity_provider.rb",
    "lib/sso_identity_provider_classes.rb",
    "lib/tasks/rorjossoagent_tasks.rake",
    "test/rorjossoagent_test.rb",
    "uninstall.rb"
  ]
  s.homepage = "http://github.com/bwalding/JOSSOAgentForROR"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Ruby JoSSO driver"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

